CREATE TABLE IF NOT EXISTS daily_sleep_detail (
    id VARCHAR PRIMARY KEY,
    day DATE,
    average_breath DOUBLE,
    average_heart_rate DOUBLE,
    average_hrv INTEGER,
    awake_time INTEGER,
    bedtime_end TIMESTAMP,
    bedtime_start TIMESTAMP,
    deep_sleep_duration INTEGER,
    efficiency INTEGER,
    latency INTEGER,
    light_sleep_duration INTEGER,
    lowest_heart_rate INTEGER,
    period INTEGER,
    readiness_score_delta INTEGER,
    rem_sleep_duration INTEGER,
    restless_periods INTEGER,
    sleep_algorithm_version VARCHAR,
    sleep_analysis_reason VARCHAR,
    sleep_score_delta INTEGER,
    time_in_bed INTEGER,
    total_sleep_duration INTEGER,
    type VARCHAR
);