CREATE TABLE IF NOT EXISTS daily_activity (
    date DATE PRIMARY KEY,
    activity_score INTEGER,
    active_calories INTEGER,
    average_met_minutes INTEGER,
    contributors JSON,
    equivalent_walking_distance DOUBLE,
    high_activity_met_minutes INTEGER,
    high_activity_time INTEGER,
    inactivity_alerts INTEGER,
    low_activity_met_minutes INTEGER,
    low_activity_time INTEGER,
    medium_activity_met_minutes INTEGER,
    medium_activity_time INTEGER,
    meters_to_target INTEGER,
    non_wear_time INTEGER,
    resting_time INTEGER,
    sedentary_met_minutes INTEGER,
    sedentary_time INTEGER,
    steps INTEGER,
    target_calories INTEGER,
    target_meters INTEGER,
    total_calories INTEGER
);
